blank_issues_enabled: true
contact_links:
  - name: Discord Community & Support
    url: https://discord.gg/9cnf49JnM
    about: Ask questions, get help, or discuss development in our Discord server.
